### ISSUE TITLE
Issue installing magento using install.php

### ISSUE THREAD

**Issue by AydinHassan** [quafzi/magento-core-installer#1]
Hi,

I stumbled across this tool on the https://github.com/magento-hackathon/magento-composer-installer repo and it advertises exactly what I want. To be able to store Magento separately from project source. 

However, I'm having issues installing Magento with this setup. It seems Magento's install script tries to put the local.xml it generates in to my vendor directory instead of the actual project.

So running a command like so:
/usr/bin/env php /Users/Aydin/sites/magentoskeleton/htdocs/install.php --license_agreement_accepted 'yes' --locale 'de_DE' --timezone 'Europe/Berlin' --db_host 'localhost' --db_name 'mageskel' --db_user 'mageskel' --db_pass 'mageskel' --url 'http://mageskel.local/' --use_rewrites 'yes' --use_secure 'no' --secure_base_url '' --use_secure_admin 'no' --admin_username 'admin' --admin_lastname 'Doe' --admin_firstname 'John' --admin_email 'john.doe@example.com' --admin_password 'somepassword' --session_save 'files' --admin_frontname 'admin' --backend_frontname 'admin' --default_currency 'EUR' --skip_url_validation 'yes' 

Results in a local.xml being created in:
/Users/Aydin/sites/magentoskeleton/vendor/jhhello/magento-ce-1.8.0.0/app/etc/local.xml

Instead of:
/Users/Aydin/sites/magentoskeleton/htdocs/app/etc/local.xml

It seems the following magento method gets the incorrect vendor directory:
http://ss.wearejh.com/l1kkb1wskp.png

Any ideas on this?
Is there potentially a lot of issues with running Magento through the vendor directory?

**Comment by quafzi** [comment]
Hi AydinHassan,

My approach to fix issues like that was to hard-copy Mage.php automatically, but you're right, there may be lots of issues with running Magento through the vendor directory, although I did not find some more. Please could you check, if your `Mage.php` got copied or symlinked? The issue should not appear, if it was copied.

**Comment by AydinHassan** [comment]
Looking at it a bit more, install.php requires Mage.php with the line:

```
require 'app/Mage.php';
```

So I'm guessing that will refer to the Mage.php in the vendor dir. I would just copy install.php over as well, but the way I am deploying with Capistrano will create a new directory for every deploy and I have the vendor directory symlinked. So I'm guessing that the copy which you have implemented in this library won't be executed if the library is already up to date.

Back to the drawing board!

**Comment by quafzi** [comment]
I changed the installer to copy all the sources now. So this issue should no longer appear, I could run the installer properly.

Concerning your Capistrano deployment, I'm not sure that this change has any effect for your deployment process. I think, you just need to call `composer install` to make sure that all your dependencies are met - and it triggers extension and core deployment (copy/symlink).

**Comment by AydinHassan** [comment]
Thanks for this, it seems to work. I'm going to send a pull request later to be able to do the deploy without doing `composer update` using the Magento Hackathon Composer Command Integrator package.
